
spring:
  datasource:
    name: page
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/page?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: root
  thymeleaf:
    mode: html
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/



mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ryan.entity
    configLocation: classpath:mybatis/mybatis-config.xml
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
server:
  port: 8081